baseURL = 'https://farnostmenin.cz/'
languageCode = 'cs-cz'
title = 'Farnost Měnín'
uglyURLs = "false"
enableEmoji = "true"
buildFuture = "true"
[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
            unsafe = true
[params]
    description = "Oficiální stránky Římskokatolické farnosti Měnín"
[menus]
    [[menu.main]]
        identifier = "aktuality"
        name = "Aktuality"
        url = "/aktuality"
        weight = "2"
    [[menu.main]]
        identifier = "zivot-ve-farnosti"
        name = "Život ve farnosti"
        url = "/zivot-ve-farnosti"
        weight = "3"
    [[menu.main]]
        identifier = "galerie"
        name = "Galerie"
        url = "/galerie"
        weight = "4"
    [[menu.main]]
        identifier = "informace"
        name = "Informace"
        url = "/informace"
        weight = "5"
    [[menu.main]]
        identifier = "dekanstvi"
        name = "Děkanství"
        url = "/dekanstvi"
        weight = "6"